### PR TITLE
Support of Mac m1

### PR DESCRIPTION
**Pull request by davideuler**

### CODE REVIEW

**Comment by zachschillaci27** [comment]
Thanks! I just ran this on my M1 Pro without a problem.

**Comment by killian-mannarelli** [comment]
It is not working on M2 ?

**Comment by zachschillaci27** [comment]
> It is not working on M2 ?

I didn't mean for that to imply it won't work on M2, just specifying my hardware. Unfortunately I don't have an M2 to test it on, but naively I would expect it to work.

**Comment by killian-mannarelli** [comment]
Working on M2

**Comment by edisonslamp** [comment]
> davideuler

hello! can't figure out how to run the model on M1:(

**Comment by edisonslamp** [comment]
> Thanks! I just ran this on my M1 Pro without a problem.

Hello! Can't figure out how to run the model on M1. Is there any manuals for this? When I follow Meta's instruction here I face the CUDA problem.

**Comment by zachschillaci27** [comment]
> 



> > Thanks! I just ran this on my M1 Pro without a problem.
> 
> Hello! Can't figure out how to run the model on M1. Is there any manuals for this? When I follow Meta's instruction here I face the CUDA problem.

Until this PR is merged, you'll need to run off of this feature branch. You can follow the steps below:

1. Add the new remote repository:
```
git remote add mps git@github.com:davideuler/codellama.git      
```

2. Fetch the changes in the new repository:
```
git fetch mps
```

3. Checkout this branch from the new remote:
```
git checkout mps/main
```

Now you should be all set to run!

**Comment by lostmygithubaccount** [comment]
does anyone have an example running on the 13B or larger? I can only load in the 7B and get hanging or various errors trying to load in the larger versions

**Review by codernex — APPROVED** [review]

**Review by Guik — APPROVED** [review]

**Comment by Domenico-Esposito** [comment]
It doesn't work for me on Mac M1. I have the following error.

I have the same error for all available examples: example_completion.py, example_infilling.py, and example_instructions.py.

```
NOTE: Redirects are currently not supported in Windows or MacOs.
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 45430) of binary: /Users/dms/.pyenv/versions/3.10.5/bin/python3.10
Traceback (most recent call last):
  File "/Users/dms/.pyenv/versions/3.10.5/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
example_instructions.py FAILED
------------------------------------------------------
```

**Comment by Rehanchy** [comment]
> It doesn't work for me on Mac M1. I have the following error.
> 
> I have the same error for all available examples: example_completion.py, example_infilling.py, and example_instructions.py.
> 
> ```
> NOTE: Redirects are currently not supported in Windows or MacOs.
> > initializing model parallel with size 1
> > initializing ddp with size 1
> > initializing pipeline with size 1
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 45430) of binary: /Users/dms/.pyenv/versions/3.10.5/bin/python3.10
> Traceback (most recent call last):
>   File "/Users/dms/.pyenv/versions/3.10.5/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/Users/dms/.pyenv/versions/3.10.5/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ======================================================
> example_instructions.py FAILED
> ------------------------------------------------------
> ```

Doesn't work for me on Mac M2, same error as this one, have I got any setups wrong?

**Comment by davideuler** [comment]
It works on my mac studio with M1 ultra, Python 3.10.10. I checked the dependencies. I'm not sure if the dependencies will cause different result.

```
pip freeze | grep -e torch -e transformer -e sentencepiece -e fairscale
ctransformers @ https://github.com/jllllll/ctransformers-cuBLAS-wheels/releases/download/AVX2/ctransformers-0.2.22+cu117-py3-none-any.whl#sha256=ac34fd73bf1c00bda40510c3bda689db420cfa37a2341e625fe6fd26355248b2
fairscale==0.4.13
pytorch-lightning==1.6.5
sentencepiece==0.1.99
torch==2.0.1
torchaudio==2.0.2
torcheval==0.0.6
torchmetrics==0.11.1
torchtnt==0.2.0
torchvision==0.16.0.dev20230816
transformers @ git+https://github.com/huggingface/transformers@baf1daa58eb2960248fd9f7c3af0ed245b8ce4af
transformers-stream-generator==0.0.4
```

**Comment by Domenico-Esposito** [comment]
> It works on my mac studio with M1 ultra, Python 3.10.10. I checked the dependencies. I'm not sure if the dependencies will cause different result.
> 
> ```
> pip freeze | grep -e torch -e transformer -e sentencepiece -e fairscale
> ctransformers @ https://github.com/jllllll/ctransformers-cuBLAS-wheels/releases/download/AVX2/ctransformers-0.2.22+cu117-py3-none-any.whl#sha256=ac34fd73bf1c00bda40510c3bda689db420cfa37a2341e625fe6fd26355248b2
> fairscale==0.4.13
> pytorch-lightning==1.6.5
> sentencepiece==0.1.99
> torch==2.0.1
> torchaudio==2.0.2
> torcheval==0.0.6
> torchmetrics==0.11.1
> torchtnt==0.2.0
> torchvision==0.16.0.dev20230816
> transformers @ git+https://github.com/huggingface/transformers@baf1daa58eb2960248fd9f7c3af0ed245b8ce4af
> transformers-stream-generator==0.0.4
> ```

Nothing, even using the same versions, I have the same error.
PS: The version "torchvision==0.16.0.dev20230816" doesn't seem to exist. I used version 0.15.2. Do you think the error is related to this?

**Review by mpu — APPROVED** [review]
Thank you for your contribution. The new code is a net improvement over the existing code that simply crashes on M1, so I'll merge it.

**Review by qsimeon — COMMENTED** [review]
.

**Pull request merged**
